# A tibble of the mutational signatures detected linked to their descriptors.
signature_description_df <- tibble::tribble(
    ~signature, ~description,
           "1",    "1",
           "2",    "2",
           "3",    "3",
           "4",    "4",
           "5",    "5",
           "6",    "6",
          "7A",    "UV",
          "7B",    "UV",
          "7C",    "UV",
          "7D",    "UV",
           "8",    "UV",
           "9",    "9",
         "10A",    "10",
         "10B",    "10",
         "10C",    "10",
          "13",    "13",
          "14",    "MSI",
          "15",    "MSI",
          "17",    "17",
        "17V2",    "17",
          "18",    "18",
          "20",    "MSI",
          "21",    "MSI",
          "26",    "26",
          "30",    "30",
          "38",    "UV",
          "45",    "artifact",
          "55",    "artifact",
         "AR1",    "artifact",
         "AR2",    "artifact",
        "N3V2",    "N3v2"
)
