# A tibble of the enriched functions to plot for final images.
# These are likely to be used for the figures.

selected_enrichments <- tibble::tribble(
    ~cancer, ~datasource,                 ~term,                                                      ~ pretty_term,
    "COAD", "WikiPathways_2019_Human",    "Focal Adhesion",                                           "Focal adhesion",
    "COAD", "Panther_2016",               "Hedgehog signaling pathway",                               "Hedgehog signaling pathway",
    "COAD", "Reactome_2016",              "Beta-catenin phosphorylation cascade",                     "β-catenin phosphorylation cascade",
    "COAD", "Reactome_2016",              "Developmental Biology",                                    "Developmental biology",
    "COAD", "Transcription_Factor_PPIs",  "SMAD2",                                                    "SMAD2",
    "COAD", "KEA_2015",                   "ATM",                                                      "ATM",
    "COAD", 'PPI_Hub_Proteins',           "YWHAZ",                                                    "YWHAZ",
    "COAD", "KEGG_2019_Human",            "mTOR signaling pathway",                                   "mTOR signaling pathway",
    "COAD", "KEGG_2019_Human",            "Hippo signaling pathway",                                  "Hippo signaling pathway",
    "COAD", "KEGG_2019_Human",            "Cellular senescence",                                      "Cellular senescence",
    "COAD", "KEGG_2019_Human",            "Apoptosis",                                                "Apoptosis",
    "COAD", "KEGG_2019_Human",            "PI3K-Akt signaling pathway",                               "PI3K-Akt signaling pathway",
    "COAD", "KEGG_2019_Human",            "Wnt signaling pathway",                                    "Wnt signaling pathway",
    "LUAD", "WikiPathways_2019_Human",    "Focal Adhesion",                                           "Focal adhesion",
    "LUAD", "Panther_2016",               "Wnt signaling pathway",                                    "Wnt signaling pathway",
    "LUAD", "GO_Biological_Process_2018", "positive regulation of MAPK cascade",                      "Positive regulation of MAPK cascade",
    "LUAD", "Transcription_Factor_PPIs",  "MYC",                                                      "MYC",
    "LUAD", "WikiPathways_2019_Human",    "RAC1/PAK1/p38/MMP2 Pathway",                               "RAC1/PAK1/p38/MMP2 Pathway",
    "LUAD", "WikiPathways_2019_Human",    "Pathways Regulating Hippo Signaling",                      "Pathways regulating hippo signaling",
    "LUAD", "PPI_Hub_Proteins",           "PRKACA",                                                   "PRKACA",
    "LUAD", "PPI_Hub_Proteins",           "PRKCA",                                                    "PRKCA",
    "LUAD", "PPI_Hub_Proteins",           "CTNNB1",                                                   "CTNNB1",
    "LUAD", "KEGG_2019_Human",            "PI3K-Akt signaling pathway",                               "PI3K-Akt signaling pathway",
    "LUAD", "KEGG_2019_Human",            "Apelin signaling pathway",                                 "Apelin signaling pathway",
    "LUAD", "BioCarta_2016",              "Chromatin Remodeling by hSWI/SNF ATP-dependent Complexes", "Chromatin remodeling by hSWI/SNF ATP-dependent complexes",
    "PAAD", "GO_Biological_Process_2018", "calcium ion transport",                                    "calcium ion transport",
    "PAAD", "Panther_2016",               "Wnt signaling pathway",                                    "Wnt signaling pathway",
    "PAAD", "WikiPathways_2019_Human",    "TGF-beta Signaling Pathway",                               "TGF-β signaling pathway",
    "PAAD", "Transcription_Factor_PPIs",  "MYC",                                                      "MYC",
    "PAAD", "Transcription_Factor_PPIs",  "SMAD1",                                                    "SMAD1",
    "PAAD", "Transcription_Factor_PPIs",  "SMAD2",                                                    "SMAD2",
    "PAAD", "Transcription_Factor_PPIs",  "SMAD3",                                                    "SMAD3",
    "PAAD", "KEA_2015",                   "PRKACA",                                                   "PRKACA",
)

cat("Loaded `selected_enrichments`.\n")
